
// Get infoUser
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm5hbWEiOiJqb25pIiwic2FsZG8iOiI3NTAwMCIsImlhdCI6MTY2OTgxMjkxMSwiZXhwIjoxNjY5ODEyOTI2fQ.Ssw-FXwyMU2tY32zm5ZLg95BsXq2bI7e9azPDNI9ieQ


// Register 
###
POST http://localhost:5000/users
Content-Type: application/json

{
  "nama": "joko",
  "email": "joko01@gmail.com",
  "password": "123",
  "confPassword": "123",
  "pin": "123456",
  "jenis_card": "blue",
  "kode_akses": "joko01",
  "ip_address": "182.2.133.21"
}


// Login 
###
POST http://localhost:5000/login
Content-Type: application/json

{
  "kode_akses": "joni01",
  "ip_address": "101.255.148.225"
}


// Refrest token 
###
GET http://localhost:5000/token



// Logout
###
DELETE http://localhost:5000/logout



// Ganti kode akses
###
POST http://localhost:5000/gantikode
Content-Type: application/json

{
  "kodeLama": "joko01",
  "kodeBaru": "joko02",
  "konfirmKodeBaru": "joko02",
  "pin": "123456",
  "email": "joko01@gmail.com",
  "ip_address": "101.255.148.225"
}


// Trasnfer Saldo
###
POST http://localhost:5000/transfer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm5hbWEiOiJqb25pIiwiaWF0IjoxNjY5ODAyOTAwLCJleHAiOjE2Njk4MDI5MjB9.HBh43PTKgqmlDXS61CoDT-ymIoOJC7B8RzNIw0xIMLY
Content-Type: application/json

{
  "userId": 6,
  "saldoTf": "25000",
  "noTujuan": "2122853427"
}


// cek nomer rekening
###
POST http://localhost:5000/ceknomor
Content-Type: application/json

{
  "no_rek": "2122853427"
}