
// Get infoUser
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWEiOiJtdWhhbW1hZCBha2JhciIsImlhdCI6MTY3MDEzOTUxMywiZXhwIjoxNjcwMTM5NTMzfQ.YU-r5VnCNipdG-McjQUOzE4yKs3rJdaj8IlIw1qFSuk


// Register 
###
POST http://localhost:5000/users
Content-Type: application/json

{
  "nama": "joko",
  "email": "joko01@gmail.com",
  "password": "123",
  "confPassword": "123",
  "pin": "123456",
  "jenis_card": "blue",
  "kode_akses": "joko01",
  "ip_address": "182.2.133.21"
}


// Login 
###
POST http://localhost:5000/login
Content-Type: application/json

{
  "kode_akses": "akbar1",
  "ip_address": "101.255.148.225"
}


// Refrest token 
###
GET http://localhost:5000/token



// Logout
###
DELETE http://localhost:5000/logout



// Ganti kode akses
###
POST http://localhost:5000/gantikode
Content-Type: application/json

{
  "kodeLama": "joko01",
  "kodeBaru": "joko02",
  "konfirmKodeBaru": "joko02",
  "pin": "123456",
  "email": "joko01@gmail.com",
  "ip_address": "101.255.148.225"
}


// Trasnfer Saldo
###
POST http://localhost:5000/transfer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm5hbWEiOiJqb25pIiwic2FsZG8iOiIzNTAwMCIsImlhdCI6MTY2OTk5MjQyNiwiZXhwIjoxNjY5OTkyNDQxfQ.IFr6fXiy9_vyj2V6yLICVP_4qCZe0dipJ8kcTvENdhM
Content-Type: application/json

{
  "saldoTf": "5000",
  "noTujuan": "8122316625"
}


// cek nomer rekening
###
POST http://localhost:5000/ceknomor
Content-Type: application/json

{
  "no_rek": "2122853427"
}


// tambah norek antar bank
###
POST http://localhost:5000/daftar_antarbank
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWEiOiJtdWhhbW1hZCBha2JhciIsImlhdCI6MTY3MDE2ODY3NiwiZXhwIjoxNjcwMTY4Njk2fQ.3RiTA1b5IO5sZrfgnJavb2sRHaGFIkVGAPuL3VtcIZg
Content-Type: application/json

{
  "no_rek": "1122411727",
  "bank": "BNI"
}


// tambah norek antar rekening
###
POST http://localhost:5000/daftar_antarrekening
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm5hbWEiOiJqb25pIiwic2FsZG8iOiI3NTAwMCIsImlhdCI6MTY2OTk3NzI1NywiZXhwIjoxNjY5OTc3MjcyfQ.2PCLuPgSz0hph-KkgNmkqT67dwwq4Sful8nmSNFtnPw
Content-Type: application/json

{
  "no_rek": "8122316625"
}


// ambil list bank lain
###
POST http://localhost:5000/list_banklain
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm5hbWEiOiJqb25pIiwic2FsZG8iOiIzMDAwMCIsImlhdCI6MTY3MDA5MDE5MSwiZXhwIjoxNjcwMDkwMjA2fQ.MYLkAFBNu6-HyoEJciI-py3JSmDOSphC4aofSDqaUIU
Content-Type: application/json

{
  "bank": "BNI"
}


// ambil list bank
###
GET http://localhost:5000/listbank